/*General definitions for the proyect*/
const MAXLENGTHWENG = 3;
const MAXQUANTQUESTIONS = 3;
const MAXLENGTHMAIN = 50;
const NUMBEROFOPTIONS = 3;
const MAXLENGTHARROPTS = MAXLENGTHMAIN * NUMBEROFOPTIONS;
const IDWORD = 0;
const WENG = 1;
const WSPA = 2;
const LEVEL = 3;

export {MAXLENGTHWENG, MAXLENGTHMAIN, MAXQUANTQUESTIONS, MAXLENGTHARROPTS,
		NUMBEROFOPTIONS,
	    IDWORD, WENG, WSPA, LEVEL};